title: GoldSim Tutorial

### Theme
# theme: jekyll-theme-cayman
remote_theme: pmarsceill/just-the-docs

### Color scheme supports "light" (default) and "dark"
color_scheme: light

aux_links:
  "Project Template on GitHub":
    - "//github.com/luquelab/project_template"


favicon_ico: "logo.ico"
logo: "logo.png"

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
# Note: the main Just the Docs site does *not* use Google Analytics.
ga_tracking: G-5GZRD5J6ST
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)


